// <auto-generated />
using System;
using ClubJumana.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClubJumana.DataLayer.Migrations
{
    [DbContext(typeof(JummanaContext))]
    [Migration("20210711164439_EditSaleOrder2")]
    partial class EditSaleOrder2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Barcode", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasMaxLength(12);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BarcodeNumber")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("barcodes");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("brands");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.CategoriesSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoryFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<int>("SubCategoryFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryFK");

                    b.HasIndex("SubCategoryFK");

                    b.ToTable("categoriessubcategories");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Sku_code")
                        .HasColumnType("text");

                    b.Property<string>("StyleNum_code")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Colour", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PantoneNumber")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("colours");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("CountryFK")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("FAX")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Manufacture")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("StateProvinceRegion")
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ZipPostlCode")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("CountryFK");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("text");

                    b.Property<string>("DigitalCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("Duty")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("ExChangeRate")
                        .HasColumnType("decimal(14,5)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address1")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<decimal>("BalanceDueLCY")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BalanceLCY")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("City")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("ContactLastName")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<decimal>("CostsLCY")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CountryFK")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy_fk")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditLimitLCY")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DisplayBillAddress")
                        .HasColumnType("text");

                    b.Property<string>("DisplayShipAddress")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("FaxNo")
                        .HasColumnType("text");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSaleDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Mobile")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Phone1")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<int?>("ProvinceFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryFK");

                    b.HasIndex("CreatedBy_fk");

                    b.HasIndex("ProvinceFK");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.DepositTo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("deposittos");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<int>("VariantFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VariantFK");

                    b.ToTable("images");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Inner", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ITF14")
                        .HasColumnType("text");

                    b.Property<int>("ProductMasterFK")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProductMasterFK");

                    b.ToTable("inners");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.InnerMasterCarton", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("InnerFK")
                        .HasColumnType("int");

                    b.Property<int>("InnerQuntity")
                        .HasColumnType("int");

                    b.Property<int>("MasterCartonFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("InnerFK");

                    b.HasIndex("MasterCartonFK");

                    b.ToTable("innermastercartons");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.InventoryReport", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Change")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("NewBalance")
                        .HasColumnType("int");

                    b.Property<int>("OldBalance")
                        .HasColumnType("int");

                    b.Property<int>("ProductMasterFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProductMasterFK");

                    b.ToTable("inventoryreports");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Alert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("AsnItemsPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("AsnPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("AsnQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool?>("Checked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Diffrent")
                        .HasColumnType("int");

                    b.Property<decimal>("GrnItemsPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GrnPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("GrnQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("PoItemsPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PoPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PoQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Po_fk")
                        .HasColumnType("int");

                    b.Property<int>("ProductMaster_fk")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Po_fk");

                    b.HasIndex("ProductMaster_fk");

                    b.ToTable("items");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.MasterCarton", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ITF14")
                        .HasColumnType("text");

                    b.Property<decimal?>("Lenght")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("mastercartons");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MaterialName")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<int>("DepositToFK")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("OpenBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PaymentMethodFK")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("DepositToFK");

                    b.HasIndex("PaymentMethodFK");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.PaymentInvoice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("InvoiceFK")
                        .HasColumnType("int");

                    b.Property<int>("PaymenteFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceFK");

                    b.HasIndex("PaymenteFK");

                    b.ToTable("paymentinvoices");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("paymentmethods");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("BrandFK")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyFK")
                        .HasColumnType("int");

                    b.Property<int?>("CountryOfOrginFK")
                        .HasColumnType("int");

                    b.Property<string>("DescribeMaterial")
                        .HasColumnType("text");

                    b.Property<int?>("MaterialFK")
                        .HasColumnType("int");

                    b.Property<string>("ProductTittle")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("StyleNumber")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("BrandFK");

                    b.HasIndex("CompanyFK");

                    b.HasIndex("CountryOfOrginFK");

                    b.HasIndex("MaterialFK");

                    b.ToTable("products");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.ProductInventoryWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Aile")
                        .HasColumnType("text");

                    b.Property<string>("Bin")
                        .HasColumnType("text");

                    b.Property<int?>("Income")
                        .HasColumnType("int");

                    b.Property<int?>("Inventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("OnTheWayInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("OutCome")
                        .HasColumnType("int");

                    b.Property<int>("ProductMaster_fk")
                        .HasColumnType("int");

                    b.Property<int?>("RefundQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<int>("Warehouse_fk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductMaster_fk");

                    b.HasIndex("Warehouse_fk");

                    b.ToTable("productinventorywarehouses");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.ProductMaster", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Bundle")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("FobPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("GoodsReserved")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int>("Income")
                        .HasColumnType("int");

                    b.Property<bool>("IsRetail")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWholesale")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateInventory")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MadeIn")
                        .HasColumnType("text");

                    b.Property<string>("Margin")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("PackCount")
                        .HasColumnType("int");

                    b.Property<int?>("RefundQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("RetailPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("SKU")
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(16);

                    b.Property<DateTime?>("SaleEndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("SaleStartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Size")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("StockOnHand")
                        .HasColumnType("int");

                    b.Property<string>("StyleNumber")
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(16);

                    b.Property<bool>("Taxable")
                        .HasColumnType("bit");

                    b.Property<int>("Transit")
                        .HasColumnType("int");

                    b.Property<int?>("UOMFK")
                        .HasColumnType("int");

                    b.Property<string>("UPC")
                        .HasColumnType("text");

                    b.Property<int?>("VariantFK")
                        .HasColumnType("int");

                    b.Property<int>("VendorCode")
                        .HasColumnType("int");

                    b.Property<decimal?>("WholesalePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("UOMFK");

                    b.HasIndex("VariantFK")
                        .IsUnique();

                    b.ToTable("productmasters");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategorysubcategoreisFK")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CategorysubcategoreisFK");

                    b.ToTable("producttypes");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("GST")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal?>("HST")
                        .HasColumnType("decimal(7,4)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal?>("QST")
                        .HasColumnType("decimal(7,4)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("provinces");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<int?>("ApproveAsnUser_fk")
                        .HasColumnType("int");

                    b.Property<int?>("ApproveGrnUser_fk")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovePoUser_fk")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AsnDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("AsnSubtotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("AsnTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Asnumber")
                        .HasColumnType("int");

                    b.Property<string>("Associate")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreateOrder")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("CreatedAsn")
                        .HasColumnType("bit");

                    b.Property<bool>("CreatedGrn")
                        .HasColumnType("bit");

                    b.Property<bool>("CreatedPO")
                        .HasColumnType("bit");

                    b.Property<decimal>("CustomsDuty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DiscountDollers")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DocNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("FormSO")
                        .HasColumnType("text");

                    b.Property<decimal>("Forwarding")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Freight")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("FromWarehouse_fk")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GrnDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("GrnSubtotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GrnTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Grnumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Handling")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Insurance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ItemsAsnCount")
                        .HasColumnType("int");

                    b.Property<int?>("ItemsGrnCount")
                        .HasColumnType("int");

                    b.Property<int?>("ItemsPoCount")
                        .HasColumnType("int");

                    b.Property<decimal>("LandTransport")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Others")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Percent")
                        .HasColumnType("text");

                    b.Property<int>("PoNumber")
                        .HasColumnType("int");

                    b.Property<string>("PoStatus")
                        .HasColumnType("text");

                    b.Property<decimal?>("PoSubtotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PoTerms")
                        .HasColumnType("text");

                    b.Property<decimal?>("PoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PoType")
                        .HasColumnType("text");

                    b.Property<string>("PrivateNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("ShipAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ToWarehouse_fk")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCharges")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Vendor_fk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproveAsnUser_fk");

                    b.HasIndex("ApproveGrnUser_fk");

                    b.HasIndex("ApprovePoUser_fk");

                    b.HasIndex("FromWarehouse_fk");

                    b.HasIndex("ToWarehouse_fk");

                    b.HasIndex("Vendor_fk");

                    b.ToTable("purchaseorders");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Refund", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("text");

                    b.Property<string>("ChequeNo")
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("MessageOnRefund")
                        .HasColumnType("text");

                    b.Property<string>("MessageOnStatement")
                        .HasColumnType("text");

                    b.Property<int?>("PaymentMethodFK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RefundDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("RefundFromFK")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundTotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<int>("SaleOrderFK")
                        .HasColumnType("int");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ShippingTaxCode")
                        .HasColumnType("text");

                    b.Property<decimal>("SubtotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("TypeOfDiscount")
                        .HasColumnType("bit");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodFK");

                    b.HasIndex("RefundFromFK");

                    b.HasIndex("SaleOrderFK");

                    b.ToTable("refunds");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.RefundItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductMaster_fk")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Refund_fk")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("TaxCodeName")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductMaster_fk");

                    b.HasIndex("Refund_fk");

                    b.ToTable("refunditems");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.SaleOrder", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BillEmail")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("BillingAddress")
                        .HasColumnType("text");

                    b.Property<int?>("Cashier_fk")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CustomerMemo")
                        .HasColumnType("text");

                    b.Property<int?>("Customer_fk")
                        .HasColumnType("int");

                    b.Property<string>("DocNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(12, 6)");

                    b.Property<DateTime?>("ExpriationDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Handling")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte>("HandlingTaxCode")
                        .HasColumnType("tinyint");

                    b.Property<bool>("HaveDeposit")
                        .HasColumnType("bit");

                    b.Property<decimal>("HomeBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("HomeTotalAmt")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MessageOnInvoice")
                        .HasColumnType("text");

                    b.Property<string>("MessageOnStatment")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("OpenBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PoNumber")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ShipMethod_fk")
                        .HasColumnType("int");

                    b.Property<string>("ShipVia")
                        .HasColumnType("text");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("text");

                    b.Property<byte>("ShippingTaxCode")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SoDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("SoTotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TermPercent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrackingNo")
                        .HasColumnType("text");

                    b.Property<bool>("Type")
                        .HasColumnType("bit");

                    b.Property<int?>("Warehouse_fk")
                        .HasColumnType("int");

                    b.Property<int?>("term_fk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cashier_fk");

                    b.HasIndex("Customer_fk");

                    b.HasIndex("Warehouse_fk");

                    b.HasIndex("term_fk");

                    b.ToTable("saleorders");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.SoItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("IsAbaleToRefund")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PriceTerm")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductMaster_fk")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityRefunded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<int>("So_fk")
                        .HasColumnType("int");

                    b.Property<byte>("TaxCode")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductMaster_fk");

                    b.HasIndex("So_fk");

                    b.ToTable("soitems");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("subcategories");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.TablesVersion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("NeedToUpdate")
                        .HasColumnType("bit");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("tablesversion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Barcodes",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 2,
                            Name = "Colours",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brands",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 4,
                            Name = "Countries",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 5,
                            Name = "Materials",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 6,
                            Name = "Companies",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 7,
                            Name = "Products",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 8,
                            Name = "Categories",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 9,
                            Name = "SubCategories",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 10,
                            Name = "CategoriesSubCategories",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 11,
                            Name = "ProductTypes",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 12,
                            Name = "Varaints",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = 13,
                            Name = "Images",
                            NeedToUpdate = false,
                            RowVersion = 0L
                        });
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Tax", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(7,4)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<int>("SalesOrderFK")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderFK");

                    b.ToTable("taxes");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(7,4)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("taxrates");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.TaxRefund", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(7,4)");

                    b.Property<int>("RefundFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("RefundFK");

                    b.ToTable("taxrefunds");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Term", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("DueDateCalculation")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("terms");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.UOM", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("uoms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pcs",
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pack4",
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.User.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ActiveCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("ExpireInvitationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("SendInvitationDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserRegisterWithInvitation_fk")
                        .HasColumnType("int");

                    b.Property<int>("UserSendInvitation_fk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRegisterWithInvitation_fk")
                        .IsUnique();

                    b.HasIndex("UserSendInvitation_fk");

                    b.ToTable("invitations");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Users.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("RoleId");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ActiveCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserAvatar")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Users.UserRole", b =>
                {
                    b.Property<int>("UR_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UR_Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("userroles");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Variant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("BarcodeFK")
                        .HasColumnType("int");

                    b.Property<string>("Bundle")
                        .HasColumnType("text");

                    b.Property<int?>("ColourFK")
                        .HasColumnType("int");

                    b.Property<string>("Data1")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Data2")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Data3")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Data4")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Data5")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Data6")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal?>("FobPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsRetail")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStar")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWholesale")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastDateEdited")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("ProductFK")
                        .HasColumnType("int");

                    b.Property<int?>("ProductTypeFK")
                        .HasColumnType("int");

                    b.Property<decimal?>("PublishRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("RetailPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Size")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Sku")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("UOMFK")
                        .HasColumnType("int");

                    b.Property<decimal?>("WholesaleA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("WholesaleB")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("length")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeFK")
                        .IsUnique();

                    b.HasIndex("ColourFK");

                    b.HasIndex("ProductFK");

                    b.HasIndex("ProductTypeFK");

                    b.HasIndex("UOMFK");

                    b.ToTable("variants");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("Acountsharp")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address1")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Address3")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<double?>("Balance")
                        .HasColumnType("double");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Info1")
                        .HasColumnType("text");

                    b.Property<string>("Info2")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime>("LastUpDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("LeadTime")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Note")
                        .HasColumnName("Note")
                        .HasColumnType("text");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("text");

                    b.Property<string>("Phone1")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Phone2")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PrintOnCheckName")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TradeDiscountPercent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("vendors");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Tel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("warehouses");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.CategoriesSubCategory", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Category", "Category")
                        .WithMany("CategoriesSubCategories")
                        .HasForeignKey("CategoryFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.SubCategory", "SubCategory")
                        .WithMany("CategoriesSubCategories")
                        .HasForeignKey("SubCategoryFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Company", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Country", "Country")
                        .WithMany("Companies")
                        .HasForeignKey("CountryFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Customer", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Country", "Country")
                        .WithMany("Customers")
                        .HasForeignKey("CountryFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.Users.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("CreatedBy_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.Province", "Province")
                        .WithMany("Customers")
                        .HasForeignKey("ProvinceFK");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Image", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Variant", "Variant")
                        .WithMany("Images")
                        .HasForeignKey("VariantFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Inner", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.ProductMaster", "ProductMaster")
                        .WithMany("Inners")
                        .HasForeignKey("ProductMasterFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.InnerMasterCarton", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Inner", "Inner")
                        .WithMany("InnerMasterCartons")
                        .HasForeignKey("InnerFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.MasterCarton", "MasterCarton")
                        .WithMany("InnerMasterCartons")
                        .HasForeignKey("MasterCartonFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.InventoryReport", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.ProductMaster", "ProductMaster")
                        .WithMany("InventoryReports")
                        .HasForeignKey("ProductMasterFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Item", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("Po_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.ProductMaster", "ProductMaster")
                        .WithMany("Items")
                        .HasForeignKey("ProductMaster_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Payment", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.DepositTo", "DepositTo")
                        .WithMany("Payments")
                        .HasForeignKey("DepositToFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.PaymentInvoice", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.SaleOrder", "Invoice")
                        .WithMany("PaymentInvoices")
                        .HasForeignKey("InvoiceFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.Payment", "Payment")
                        .WithMany("PaymentInvoices")
                        .HasForeignKey("PaymenteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Product", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.Country", "CountryOfOrgin")
                        .WithMany("Products")
                        .HasForeignKey("CountryOfOrginFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.Material", "Material")
                        .WithMany("Products")
                        .HasForeignKey("MaterialFK");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.ProductInventoryWarehouse", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.ProductMaster", "ProductMaster")
                        .WithMany("ProductInventoryWarehouses")
                        .HasForeignKey("ProductMaster_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.Warehouse", "Warehouse")
                        .WithMany("ProductInventoryWarehouses")
                        .HasForeignKey("Warehouse_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.ProductMaster", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.UOM", "Uom")
                        .WithMany("ProductMasters")
                        .HasForeignKey("UOMFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.Variant", "Variant")
                        .WithOne("ProductMaster")
                        .HasForeignKey("ClubJumana.DataLayer.Entities.ProductMaster", "VariantFK");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.ProductType", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.CategoriesSubCategory", "CategoriesSubCategory")
                        .WithMany("ProductTypes")
                        .HasForeignKey("CategorysubcategoreisFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Users.User", "UserCreateAsn")
                        .WithMany("CreateAsn")
                        .HasForeignKey("ApproveAsnUser_fk");

                    b.HasOne("ClubJumana.DataLayer.Entities.Users.User", "UserCreateGrn")
                        .WithMany("CreateGrn")
                        .HasForeignKey("ApproveGrnUser_fk");

                    b.HasOne("ClubJumana.DataLayer.Entities.Users.User", "UserCreatePo")
                        .WithMany("CreatePo")
                        .HasForeignKey("ApprovePoUser_fk");

                    b.HasOne("ClubJumana.DataLayer.Entities.Warehouse", "FromWarehouse")
                        .WithMany("POFromWarehouse")
                        .HasForeignKey("FromWarehouse_fk");

                    b.HasOne("ClubJumana.DataLayer.Entities.Warehouse", "ToWarehouse")
                        .WithMany("PoToWareHose")
                        .HasForeignKey("ToWarehouse_fk");

                    b.HasOne("ClubJumana.DataLayer.Entities.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("Vendor_fk");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Refund", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentMethodFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.DepositTo", "RefundFrom")
                        .WithMany("Refunds")
                        .HasForeignKey("RefundFromFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.SaleOrder", "SaleOrder")
                        .WithMany("Refunds")
                        .HasForeignKey("SaleOrderFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.RefundItem", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.ProductMaster", "ProductMaster")
                        .WithMany("RefundItems")
                        .HasForeignKey("ProductMaster_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.Refund", "Refund")
                        .WithMany("RefundItems")
                        .HasForeignKey("Refund_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.SaleOrder", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Users.User", "User")
                        .WithMany("SaleOrders")
                        .HasForeignKey("Cashier_fk");

                    b.HasOne("ClubJumana.DataLayer.Entities.Customer", "Customer")
                        .WithMany("SaleOrders")
                        .HasForeignKey("Customer_fk");

                    b.HasOne("ClubJumana.DataLayer.Entities.Warehouse", "Warehouse")
                        .WithMany("SaleOrders")
                        .HasForeignKey("Warehouse_fk");

                    b.HasOne("ClubJumana.DataLayer.Entities.Term", "Term")
                        .WithMany("SaleOrders")
                        .HasForeignKey("term_fk");
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.SoItem", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.ProductMaster", "ProductMaster")
                        .WithMany("SoItems")
                        .HasForeignKey("ProductMaster_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.SaleOrder", "SaleOrder")
                        .WithMany("SoItems")
                        .HasForeignKey("So_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Tax", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.SaleOrder", "SaleOrder")
                        .WithMany("Taxes")
                        .HasForeignKey("SalesOrderFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.TaxRefund", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Refund", "Refund")
                        .WithMany("TaxesRefunds")
                        .HasForeignKey("RefundFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.User.Invitation", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Users.User", "UserRegisterWithInvitation")
                        .WithOne("RegisterWithInvitation")
                        .HasForeignKey("ClubJumana.DataLayer.Entities.User.Invitation", "UserRegisterWithInvitation_fk");

                    b.HasOne("ClubJumana.DataLayer.Entities.Users.User", "UserSendInvitation")
                        .WithMany("SendInvitations")
                        .HasForeignKey("UserSendInvitation_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Users.UserRole", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubJumana.DataLayer.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubJumana.DataLayer.Entities.Variant", b =>
                {
                    b.HasOne("ClubJumana.DataLayer.Entities.Barcode", "Barcode")
                        .WithOne("Variant")
                        .HasForeignKey("ClubJumana.DataLayer.Entities.Variant", "BarcodeFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.Colour", "Colour")
                        .WithMany("Variants")
                        .HasForeignKey("ColourFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.ProductType", "ProductType")
                        .WithMany("Variants")
                        .HasForeignKey("ProductTypeFK");

                    b.HasOne("ClubJumana.DataLayer.Entities.UOM", "Uom")
                        .WithMany("Variants")
                        .HasForeignKey("UOMFK");
                });
#pragma warning restore 612, 618
        }
    }
}
